# Generated by Django 4.1.7 on 2023-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produtos_tamanho_alter_produtos_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='clientes',
            name='senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
