# Generated by Django 4.1.7 on 2023-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_remove_produtos_categoria_clientes_senha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ano', models.PositiveIntegerField()),
                ('foto', models.ImageField(upload_to='produtos')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedidositens',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidositens',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='clientes',
            name='celular',
            field=models.CharField(default='0000', max_length=15),
        ),
        migrations.AddField(
            model_name='clientes',
            name='genero',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.DeleteModel(
            name='Enderecos',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.DeleteModel(
            name='PedidosItens',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
